version: '3.7'

name: online-store

services:
  postgres:
   image: bitnami/postgresql:13.16.0
   ports:
     - '5433:5432'
   environment:
    - POSTGRES_USER=docker
    - POSTGRES_PASSWORD=docker
    - POSTGRES_DB=OnlineSelling
